### ISSUE TITLE
Color scheme a mess, after deleting ~/.emacs.d

### ISSUE THREAD

**Issue by sakh1979** [jhamrick/emacs#19]
@jhamrick I deleted my ~/.emacs.d folder, and ran /.bootstrap.sh for a fresh install.

After doing that, my highlighting (e.g. magit's highlighting, and parentheses matching highlight) looks terrible, and other color schemes are messed up too. Have you faced this issue before? If so, could you please let me know how you resolved it?

I know for sure, it is not related to your emacs configuration. But, I have no clue what might be causing it.

Thanks,
Sagun

**Comment by cpbl** [comment]
Is this on "emacs -nw" , ie terminal, emacs?
I don't know what's the cause, but colours for me, while nice in graphical (windowed) emacs, have become nearly impossible in tty: bright green background, nearly invisible highlighting...
This could be unrelated.

**Comment by sakh1979** [comment]
@cpbl No, the colors in terminal looks very good. Matter of fact, I like the terminal colors.

My windowed emacs color is whats messed up. They weren't like that before, it started after I deleted my ~/.emacs.d folder, and did a clean install of all the plugins.

**Comment by sakh1979** [comment]
Just a hunch, but the colors in magit buffer looks intermingled between Solarized Dark and Solarized Light. Could that somehow happen? Do you guys see that?

That is a really weird observation!

**Comment by sakh1979** [comment]
I added/changed following lines in the custom.el file:

(set-frame-parameter nil 'background-mode 'dark)
(load-theme 'solarized t)

At first, it did seem to work, but upon further investigation it still does feel quite right.

**Comment by sakh1979** [comment]
Issue is fixed after updating/installing the latest solarized repo.
