### ISSUE TITLE
recall previous line not working

### ISSUE THREAD

**Issue by RobbieScott** [jhamrick/emacs#22]
Hi,

Your emacs-python setup is generally great. I think I have it all working fine (except for pyflakes which I don't want anyway). However when i press the up arrow in the ipython interpreter the cursor just moves up rather than recalling the previous line. This greatly reduces my productivity. Is this standard behaviour or just a mistake I've made. BTW I'm running it on a mac with yosemite and the latest version of emacs. Thanks

**Comment by cpbl** [comment]
This is definitely a feature. You can move your cursor up and copy/edit text like in any editing buffer.
If you want to recall a line, simply make sure you're at the prompt, and press Ctrl-up rather than just up.

**Comment by jhamrick** [comment]
Yeah, as @cpbl said it should work to press C-up and C-down to navigate through the history.

**Comment by RobbieScott** [comment]
Phew! Thank you!

**Comment by RobbieScott** [comment]
I have been running this in the mac terminal (rather than xquartz) and annoyingly the last line recall doesn�t work here. I don�t suppos eyou have any idea how to fix this do you?

Thanks

Robbie
