### ISSUE TITLE
Hi I have some problems when I install your  configuration

### ISSUE THREAD

**Issue by allen0125** [jhamrick/emacs#23]
when I run the bootstrap.sh script the system show:
root@allen-550P5C-550P7C:/home/allen/emacs# sh bootstrap.sh 
come from https://github.com/jhamrick/emacs
 * branch            master     -> FETCH_HEAD
Already up-to-date.
bootstrap.sh: 10: bootstrap.sh: [[: not found
bootstrap.sh: 14: bootstrap.sh: Syntax error: "(" unexpected
root@allen-550P5C-550P7C:/home/allen/emacs# exit
exit

what should I do?thx

**Comment by jhamrick** [comment]
I think you probably need to run the script with `bash` rather than `sh`.

**Comment by allen0125** [comment]
Thx for your answer

then I got some Error:
Error (el-get): while installing auctex: el-get: ./autogen.sh el-get could not build auctex [./autogen.sh]
Error (el-get): while installing magit: el-get: make el-get could not build magit [make EMACSBIN=/usr/bin/emacs24 docs]
Error (el-get): while installing pydoc-info: The command named 'hg' can not be found with `executable-find'

and what should I do?

**Comment by jhamrick** [comment]
`hg` is the command for mercurial, so you probably need to install
mercurial.

**Comment by Keris** [comment]
Hi, when I install your emacs configuration, I encountered following error and I don't know what to do, can you help me?
>From https://github.com/jhamrick/emacs
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Clean the above files? (y/n) y
This may overwrite existing files in your home directory. Are you sure? (y/n) y
.emacs
fatal: bad revision '.emacs'
.emacs.d
fatal: bad revision '.emacs.d'

**Comment by Keris** [comment]
Hi, when I install your emacs configuration, I encountered following error and I don't know what to do, can you help me?
>From https://github.com/jhamrick/emacs

 * branch            master     -> FETCH_HEAD

Already up-to-date.

Clean the above files? (y/n) y

This may overwrite existing files in your home directory. Are you sure? (y/n) y

.emacs

fatal: bad revision '.emacs'

.emacs.d

fatal: bad revision '.emacs.d'

**Comment by Keris** [comment]
Hi, I encountered the following errors when I install you configuration, can you help me?
>From https://github.com/jhamrick/emacs
  \* branch            master     -> FETCH_HEAD
 Already up-to-date.
 Clean the above files? (y/n) y
 This may overwrite existing files in your home directory. Are you sure? (y/n) y
 .emacs
 fatal: bad revision '.emacs'
 .emacs.d
 fatal: bad revision '.emacs.d'
