### ISSUE TITLE
Errors on first set-up: matlab-mode, pydoc-info, autostart.el

### ISSUE THREAD

**Issue by MartinHeroux** [jhamrick/emacs#27]
Dear Jessica, 

BACKGROUND
I found this repo after reading your intro to emacs blog; it was very useful and great for a beginner in emacs like myself.  While it might be silly for beginner to try using a fancy configuration (which adds many tools that I think would be useful, but that I would not be able to implement myself for a few months...or years!).

MY SYSTEM
- linux Mint 17.2 (currently the most recent release) on a 64-bit system.
- I updated git to version 2.6 (the version that ships with Mint is quite old, and your script prompted me that a newer version of git was required).
- I initially installed emacs 24.3.1, because that is the version you tested the configuration on.

THE PROBLEM
After running your bash script, I opened Emacs. It did lots of cool looking stuff with el-get, but at the end I had the following error messages:

<code> Error (el-get): while installing magit: Package magit requires Emacs version 24.4 or higher, but the current Emacs is only version 24.3.1  </code>
<code> Error (el-get): while installing matlab-mode: The command named 'cvs' can not be found with `executable-find' </code>
<code>  Error (el-get): while installing pydoc-info: The command named 'hg' can not be found with `executable-find' </code>
<code> Warning (initialization): An error occurred while loading `/home/martin/.emacs': </code>
<code> File error: Cannot open load file, magit </code>

FIX DID NOT WORK
Because of the first error message, I decided to start over and install Emacs version 24.5. I ran the bash script and started Emacs again, then got the following error message:
 
<code> Error (el-get): while installing matlab-mode: The command named 'cvs' can not be found with `executable-find' </code>
<code> Error (el-get): while installing pydoc-info: The command named 'hg' can not be found with `executable-find '</code>
<code> Warning (initialization): An error occurred while loading `/home/martin/.emacs': </code>
<code> File error: Cannot open load file, no such file or directory, /home/martin/.emacs.d/el-get/nxhtml/autostart.el </code>

ASSISTANCE APPRECIATED
I am quite new to emacs and any help guidance would be appreciated. If the best thing is to start from a vanilla install and configuration for now until I better understand emacs, I would understand (although, there is nothing wrong with vanilla!). If there is an easy fix to the issues (for either Emacs 24.3 or Emacs 24.5), that would be great.

Regards,

Marty

**Comment by jhamrick** [comment]
From the following error messages, it looks like you need to install CVS (which provides the `cvs`) command and Mercurial (which provides the `hg` command):

> The command named 'cvs' can not be found with executable-find

and 

> The command named 'hg' can not be found with executable-find

**Comment by MartinHeroux** [comment]
Thank you for the quick reply.

I tried re-running your script after installing CVS and Mercurial, but unfortunately I still had problems. I have decided to start from 'vanilla' emacs and earn my strips as it were.
