### ISSUE TITLE
nxhtml/mumamo

### ISSUE THREAD

**Issue by steven-murray** [jhamrick/emacs#29]
Hi,

Thanks for this, it looks really good. 

I just installed it on Ubuntu 15.10, with default versions for everything. After making sure I installed all the dependencies, the installation still came up with an error, that the file ``~/.emacs.d/el-get/nxhtml/autostart.el`` didn't exist. 

I fixed this by modifying a line in ``~/emacs.d/settings/mumamo-settings.el``, changing ``~/.emacs.d/el-get/nxhtml/autostart.el`` to ``~/.emacs.d/el-get/nxhtml/elisp/autostart.el``, and everything seems to have worked. 

Perhaps this should be a warning on the README.

Cheers,
Steven

**Comment by leonardblier** [comment]
Hi,

I had the same problem, and solved it the same way. I made a PR about this, but maybe it wasn't a good solution : according to nxhtml's documentation, the file should be in `nxhtml/autostart.el`. Maybe there is a problem in the installation.

Cheers,
Léonard

**Comment by steven-murray** [comment]
Strange. Oh well, it's all working for me :)

**Comment by jhamrick** [comment]
Thanks for reporting this! Closing as this should be fixed now by #28
